### ISSUE TITLE
web checklist

### ISSUE THREAD

**Issue by vforgione** [UrbanCCD-UChicago/plenario2#126]
- data set actions when logged in
  - [x] create a meta
  - [x] update a meta
    - [ ] only if it isn't active/ready -- #127
    - [ ] request to admins if it is -- #128
  - [ ] delete a meta
    - [ ] only if it isn't active/ready
    - [ ] request to admins if it is
  - [x] submit meta for approval
  - [x] create fields from meta detail
  - [x] update fields iff meta isn't ready
  - [ ] delete fields iff meta isn't ready
  - [x] create constraints from meta detail
  - [x] update constraints iff meta isn't ready
  - [ ] delete constraints iff meta isn't ready
  - [x] create virtual dates from meta detail
  - [x] update virtual dates iff meta isn't ready
  - [ ] delete virtual dates iff meta isn't ready
  - [x] create virtual points from meta detail
  - [ ] update virtual points iff meta isn't ready
  - [ ] delete virtual points iff meta isn't ready

- admin actions when logged in
  - [x] approve a data set
  - [x] reject a data set

- etl jobs
  - [x] start etl on demand from meta detail
  - [ ] limit memory consumption
  - [ ] create fsm on schema for states
  - [ ] create actions that call fsm funcs

**Comment by vforgione** [comment]
lots of updates with #153
