### ISSUE TITLE
Constrain Meta Update to Not Ready

### ISSUE THREAD

**Issue by vforgione** [UrbanCCD-UChicago/plenario2#127]
if a meta's state is `ready` then do not allow changes to the meta's data

- [x] needs a check in the changeset
- [x] needs to implement check in controller
- [x] needs to have message in template

ref #126

**Comment by vforgione** [comment]
closed with #153
