### ISSUE TITLE
Populate meta object of response

### ISSUE THREAD

**Issue by HeyZoos** [UrbanCCD-UChicago/plenario2#282]
- [ ] Should include correct counts for the number of data objects on the current page
- [ ] Should include links for pagination (if applicable)
- [ ] Should include query arguments (if applicable)
